name: Build Player
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/onionui/miyoomini-toolchain:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: arm-linux-gnueabihf-gcc main.c -o player -lSDL2
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: player-bin
          path: player
