name: Build MiyooPod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install ARM cross-compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Build
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm
          GOARM: 7
          CC: arm-linux-gnueabihf-gcc
        run: |
          go get github.com/hajimehoshi/go-mp3
          go build -ldflags="-s -w" -o MiyooPod

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiyooPod-Binary
          path: MiyooPod
