name: Build Player
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup ARM Compiler & SDL2
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf libsdl2-dev:armhf

      - name: Build binary
        run: arm-linux-gnueabihf-gcc main.c -o player -lSDL2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: player-bin
          path: player
